### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by chooper100** [chooper100/isonline-backend#2]
TODO
`https://scratchtools.tk/isonline/api/v1/[username]/[key]/delete`
Deletes record on database

**Comment by WorldLanguages** [comment]
Note we don't have background permissions so we can't add an uninstall extension page

**Comment by chooper100** [comment]
Is the background permission required for the setUninstallUrl then?
(I thought it wasn't, and it doesn't make sense that it should be needed)

**Comment by WorldLanguages** [comment]
It sadly is :(

Setting the uninstall URL on a content script just logs an error while doing the same on background.js works

**Comment by chooper100** [comment]
Ok, an uninstall script isn't a major thing anyway
I'll still keep this on the todo list anyway in case we do add the background permission in the future

**Comment by WorldLanguages** [comment]
Update - I didn't notice the background permission wasn't needed for background scripts 🤦‍♂️

**Comment by chooper100** [comment]
🤦‍♂️

**Comment by chooper100** [comment]
Uninstall page + API script now available
