### ISSUE TITLE
Non cryptographically secure random

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [chooper100/isonline-backend#3]
Use `openssl_random_pseudo_bytes` not `rand`

**Comment by chooper100** [comment]
Good catch!

**Comment by chooper100** [comment]
Just so you are aware, I have plans to implement this change but with exams it might be a while before that happens (as the change will come with new API pages for automatically regenerating everyone's key)

**Comment by chooper100** [comment]
Issue has now been resolved, thanks again!
